"""Add session_token column

Revision ID: 584e8900914a
Revises: 
Create Date: 2025-01-13 22:07:33.107036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584e8900914a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_description'), ['description'], unique=False,if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_document_name'), ['name'], unique=False,if_not_exists=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('session_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_session_token', ['session_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_expiry')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_name'))
        batch_op.drop_index(batch_op.f('ix_document_description'))

    # ### end Alembic commands ###
